server:
  port: 8082
  servlet:
    context-path: /simlearn/authentication
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: anandpsingh7@gmail.com
    password: wqrv yqpw qxie jixi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts