server:
  servlet:
    context-path: /simlearn
spring:
  security:
    user:
      name: 5595832005
      password: 5dceeeb7-47f3-4dc9-8f00-2845af1da8d2
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts